services:
  server:
    container_name: server
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hng-task
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - "5050:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=bodunrindavidbond@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=david
  #   restart: always
  #   depends_on:
  #     - postgres

volumes:
  data:
